@apiHost = http://localhost:3000

### Getting a list of users
# @name allUsers

### delete person
DELETE {{apiHost}}/api/movie

### Заполнение данных в массив 
POST {{apiHost}}/api/add
Content-Type: application/json
{}

### Редактирование данных фильма
PATCH {{apiHost}}/api/create

### Удаление фильма
DELETE {{apiHost}}/movie/delete

### Получение фильмов 
GET {{apiHost}}/movies
Content-Type: application/json
{
    "year": 1995,
    "actor": "Chook",
    "genre": "war",
    "title": "Fight"    
}

###

GET {{apiHost}}/movie/11