@apiHost = http://localhost:3000


### Getting a list of users
# @name allUsers
GET {{apiHost}}/hello

###
@userId = {{allUsers.response.body.users[1].id}}
@created = 2025-07-01T06:07:32.544Z

### new person (why not PUT)
POST {{apiHost}}/api/users/add
Content-Type: application/json

{
    "user": {
        "id": 1,
        "created": "{{created}}",
        "name": "dfgdfg",
        "email": "dfgdfgdgfg"
    }
}

### delete person
DELETE {{apiHost}}/api/users/delete/{{userId}}

### edit person
PUT {{apiHost}}/api/users/update
Content-Type: application/json

{
    "user": {
        "id": {{userId}},
        "created": "{{created}}",
        "name": "first",
        "email": "second" 
        }
}

###

POST {{apiHost}}/hello
Content-Type: application/json

{
    "name": "Vladimir"
}



//добавить входные параметры через дайрект фильтер погода типо и т.д.
//удаление и фильтрация фильмов по id 
### Заполнение данных в массив let

POST {{apiHost}}/new
Content-Type: application/json

{
    "data": {
        "title": "Fight",
        "genres" : ["war", "documental"],
        "actors": ["Pupa" , "Lupa", "Chook"],
        "year": 1996
    }
}

### Получение данных

GET {{apiHost}}/movies
Content-Type: application/json

{
    "year": 1995,
    "actor": "Chook",
    "genre": "war",
    "title": "Fight"    
}
